package com.pbj.loccar.view;
import com.pbj.loccar.control.UsuarioControl;
import com.pbj.loccar.view.tables.UsuarioTable;
import javax.swing.JOptionPane;

/**
 *
 * @author Akr-Taku
 * 
 * JFrame que faz O CRUD do Usuário Pode Não ser Visivel alguns Usuarios
 */
public class JFrameCadastroUsuario extends javax.swing.JFrame {

    
    UsuarioTable tableModel; //Cria uma Table
  
    public JFrameCadastroUsuario() {
        initComponents();
        
       //Inicia os botões Excluir e Alterar Como não editaveis
       jButtonExcluir.setEnabled(false);
       jButtonAlterar.setEnabled(false);
       //Instancia a Tabela
       tableModel = new UsuarioTable();
       //Popula a tabela a partir de uma List recebida do bd
       tableModel.addLista(UsuarioControl.lerUsuario());
       //Seta o modelo da tabela na tabela do Frame
       jTableUser.setModel(tableModel);   
        
    }
    
    //Recebe o Indice do da String e retorna de Acordo com o UsuarioTable
    private String pegarTexto(int i){
              
        String user[] = tableModel.getUsuario(jTableUser.getSelectedRow());
     
        return user[i];
    }
    //Metodo interno que Limpa todos os textFields
    private void limparTexto(){
        
        txtLogin.setText("");
        txtNome.setText("");
        jPasswordField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBotoesUser = new javax.swing.JPanel();
        jPanelCadastroUser = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelNvAcess = new javax.swing.JLabel();
        jComboBoxAcesso = new javax.swing.JComboBox<>();
        jLabelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanelCadastroUser.setBorder(javax.swing.BorderFactory.createTitledBorder("Novo Usuário"));

        jLabelLogin.setText("Login");

        jLabelPass.setText("Senha");

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        jLabelNvAcess.setText("Nível de Acesso");

        jComboBoxAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parceiro", "Admin" }));

        jLabelNome.setText("Nome");

        javax.swing.GroupLayout jPanelCadastroUserLayout = new javax.swing.GroupLayout(jPanelCadastroUser);
        jPanelCadastroUser.setLayout(jPanelCadastroUserLayout);
        jPanelCadastroUserLayout.setHorizontalGroup(
            jPanelCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNvAcess)
                    .addComponent(jComboBoxAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroUserLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPass)
                            .addComponent(jLabelNome))
                        .addGap(254, 254, 254))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroUserLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))))
        );
        jPanelCadastroUserLayout.setVerticalGroup(
            jPanelCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin)
                    .addComponent(jLabelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPass)
                    .addComponent(jLabelNvAcess))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUserMouseClicked(evt);
            }
        });
        jTableUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableUserKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUser);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonNew.setText("Novo");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesUserLayout = new javax.swing.GroupLayout(jPanelBotoesUser);
        jPanelBotoesUser.setLayout(jPanelBotoesUserLayout);
        jPanelBotoesUserLayout.setHorizontalGroup(
            jPanelBotoesUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoesUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCadastroUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelBotoesUserLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jPanelBotoesUserLayout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvar)
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        jPanelBotoesUserLayout.setVerticalGroup(
            jPanelBotoesUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanelBotoesUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonNew))
                .addGap(45, 45, 45))
        );

        getContentPane().add(jPanelBotoesUser);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        //Ao Clicar no botão a Janela é fechada.
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
     //Botão de salvar Usuario ao. Clicar o Usuario é Salvo no Banco de dados.
       
     //Verifica se algum Campo é vazio
       if("".equals(txtLogin.getText()) || "".equals(txtNome.getText()) || jPasswordField.getPassword().length == 0 ){
           
           JOptionPane.showMessageDialog(null, "Não é Possivel Salvar Campos Vazios","",JOptionPane.ERROR_MESSAGE);
       }
       else{  //salva Caso não existam Campos Vazios
           
       UsuarioControl.salvarUsuario(txtLogin.getText(), txtNome.getText(), new String(jPasswordField.getPassword()), (String) jComboBoxAcesso.getSelectedItem());
       tableModel.removeAll(); // Remova para não haver Duplicação
       tableModel.addLista(UsuarioControl.lerUsuario()); // Recarrega a Tabela
       limparTexto(); //Limpa os campos após o salvamento dos coisas
       
       }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // Ao Clicar neste Botão é Atualizado um Registro no Banco de dados
        // Botão somente é clickavel caso uma linha da tabela esteja selecionada
        if(jTableUser.getSelectedRow() != -1 )
        {
            //Altera chamando metodo do Control
            UsuarioControl.atualizarUsuario(Integer.parseInt(pegarTexto(0)),txtLogin.getText(), txtNome.getText(), new String(jPasswordField.getPassword()), (String) jComboBoxAcesso.getSelectedItem());
            tableModel.removeAll();//Remova para não haver Duplicação
            tableModel.addLista(UsuarioControl.lerUsuario());//Recarrega a Tabela
            limparTexto(); //Limpa os campos após o salvamento dos coisas
            jButtonExcluir.setEnabled(false);//Seta como não editavel para não haver erros
            jButtonAlterar.setEnabled(false);//Seta como não editavel para não haver erros
        
        }
               
       
               
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUserMouseClicked
        // Faz com que a os campos de texto mostrem o que está na tabela apartir do click do mouse
        jButtonSalvar.setEnabled(false);//Seta o Salvar como não editavel para não duplicar nada no banco
        jButtonExcluir.setEnabled(true);//Seta como editavel botões de excluir e alterar
        jButtonAlterar.setEnabled(true);
        //Pega os dados e seta em seus textFields
        txtLogin.setText(pegarTexto(1));
        txtNome.setText(pegarTexto(2));
        jPasswordField.setText(pegarTexto(4)); 
        jComboBoxAcesso.setSelectedItem(pegarTexto(3));
        
        
    }//GEN-LAST:event_jTableUserMouseClicked

    private void jTableUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableUserKeyReleased
        //Faz com que a os campos de texto mostrem o que está na tabela apartir das setinhas
        //Faz a mesma coisa que o evento do mouse Click
        jButtonSalvar.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jButtonAlterar.setEnabled(true);
        txtLogin.setText(pegarTexto(1));
        txtNome.setText(pegarTexto(2));
        jPasswordField.setText(pegarTexto(4));
        jComboBoxAcesso.setSelectedItem(pegarTexto(3));
    }//GEN-LAST:event_jTableUserKeyReleased

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // Botão habilita a criação de novo Usuario:
        
        jButtonSalvar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        limparTexto();
        
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        //Ação de Excluir do Registro
        
        int resp =  JOptionPane.showConfirmDialog(rootPane, "Tem Certeza que deseja Exluir?");
        
        if (resp == 0){//Somente apaga caso o verificador seja Sim
            
            UsuarioControl.apagarUsuario(Integer.parseInt(pegarTexto(0)));
        }
        tableModel.removeAll(); // Remova para não haver Duplicação
        tableModel.addLista(UsuarioControl.lerUsuario()); // Recarrega a Tabela
        limparTexto(); //Limpa os campos após o salvamento dos coisas
        jButtonExcluir.setEnabled(false);//Seta botões e excluir a alterar como não editaveis
        jButtonAlterar.setEnabled(false);
        
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxAcesso;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNvAcess;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JPanel jPanelBotoesUser;
    private javax.swing.JPanel jPanelCadastroUser;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUser;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
