/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pbj.loccar.view;

import java.awt.GridBagLayout;



/**
 *
 * @author Akr-Taku
 */
public final class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    
    
    public JFrameMain() {      
        initComponents();
        setLocationRelativeTo(null);
        setLayout(new GridBagLayout());
        jMenuBarBarraPrincipal.setVisible(false);
        
    }
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jButtonLogar = new javax.swing.JButton();
        jComboBoxDominio = new javax.swing.JComboBox<>();
        txtSenha = new javax.swing.JPasswordField();
        jLabelDominio = new javax.swing.JLabel();
        jMenuBarBarraPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuDeslogar = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCadasVeiculo = new javax.swing.JMenuItem();
        jMenuItemCadasCliente = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuConsVeiculos = new javax.swing.JMenuItem();
        jMenuConsClientes = new javax.swing.JMenuItem();
        jMenuLocacao = new javax.swing.JMenu();
        jMenuItemLocar = new javax.swing.JMenuItem();
        jMenuItemDevolver = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuFatLoc = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LocCar");

        jPanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("Autentificação"));

        jLabelLogin.setText("Login");

        jLabelSenha.setText("Senha");

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        jButtonLogar.setText("Logar");
        jButtonLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogarActionPerformed(evt);
            }
        });

        jComboBoxDominio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionário", "Administrador" }));
        jComboBoxDominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDominioActionPerformed(evt);
            }
        });

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        jLabelDominio.setText("Domínio");

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelLoginLayout.createSequentialGroup()
                                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSenha)
                                    .addComponent(jLabelLogin))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(txtSenha)))
                            .addGroup(jPanelLoginLayout.createSequentialGroup()
                                .addComponent(jLabelDominio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxDominio, 0, 195, Short.MAX_VALUE))))
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButtonLogar)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSenha))
                .addGap(18, 18, 18)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDominio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButtonLogar)
                .addContainerGap())
        );

        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(51, 102, 0));
        jMenu1.setText("[Logado]");

        jMenuDeslogar.setText("Deslogar");
        jMenuDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDeslogarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDeslogar);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSair);

        jMenuBarBarraPrincipal.add(jMenu1);

        jMenuCadastros.setText("Cadastro");

        jMenuItemCadasVeiculo.setText("Cadastrar Veiculo");
        jMenuItemCadasVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadasVeiculoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadasVeiculo);

        jMenuItemCadasCliente.setText("Cadastrar Cliente");
        jMenuItemCadasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadasClienteActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadasCliente);

        jMenuBarBarraPrincipal.add(jMenuCadastros);

        jMenuConsultas.setText("Consulta");

        jMenuConsVeiculos.setText("Consultar Veiculos");
        jMenuConsVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsVeiculosActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuConsVeiculos);

        jMenuConsClientes.setText("Consultar Clientes");
        jMenuConsClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsClientesActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuConsClientes);

        jMenuBarBarraPrincipal.add(jMenuConsultas);

        jMenuLocacao.setText("Locação");

        jMenuItemLocar.setText("Locar Veículo");
        jMenuItemLocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLocarActionPerformed(evt);
            }
        });
        jMenuLocacao.add(jMenuItemLocar);

        jMenuItemDevolver.setText("Devolver Veículo");
        jMenuItemDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDevolverActionPerformed(evt);
            }
        });
        jMenuLocacao.add(jMenuItemDevolver);

        jMenuBarBarraPrincipal.add(jMenuLocacao);

        jMenuRelatorios.setText("Relatórios");

        jMenuFatLoc.setText("Faturas de Locação");
        jMenuFatLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFatLocActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuFatLoc);

        jMenuBarBarraPrincipal.add(jMenuRelatorios);

        jMenuAjuda.setText("Ajuda");
        jMenuBarBarraPrincipal.add(jMenuAjuda);

        setJMenuBar(jMenuBarBarraPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadasVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadasVeiculoActionPerformed
        // TODO add your handling code here:
        new JFrameCadastroVeiculo().setVisible(true);
        
    }//GEN-LAST:event_jMenuItemCadasVeiculoActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void jComboBoxDominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDominioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDominioActionPerformed

    private void jButtonLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogarActionPerformed

        jPanelLogin.setVisible(false);

        jMenuBarBarraPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonLogarActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void jMenuItemCadasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadasClienteActionPerformed
        // TODO add your handling code here:
        new JFrameCadastroCliente().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadasClienteActionPerformed

    private void jMenuConsVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsVeiculosActionPerformed
        // TODO add your handling code here:
        new JFrameConsultaVeiculos().setVisible(true);
    }//GEN-LAST:event_jMenuConsVeiculosActionPerformed

    private void jMenuConsClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsClientesActionPerformed
        // TODO add your handling code here:
        
        new JFrameConsultaClientes().setVisible(true);
    }//GEN-LAST:event_jMenuConsClientesActionPerformed

    private void jMenuItemDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDevolverActionPerformed
        // TODO add your handling code here:
        new JFrameBuscaDevol().setVisible(true);
        
    }//GEN-LAST:event_jMenuItemDevolverActionPerformed

    private void jMenuItemLocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLocarActionPerformed
        // TODO add your handling code here:
        new JFrameLocar().setVisible(true);
    }//GEN-LAST:event_jMenuItemLocarActionPerformed

    private void jMenuFatLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFatLocActionPerformed
        // TODO add your handling code here:
        
        new JFrameFaturaLoc().setVisible(true);
    }//GEN-LAST:event_jMenuFatLocActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDeslogarActionPerformed
        // TODO add your handling code here:
        jPanelLogin.setVisible(true);

        jMenuBarBarraPrincipal.setVisible(false);
    }//GEN-LAST:event_jMenuDeslogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogar;
    private javax.swing.JComboBox<String> jComboBoxDominio;
    private javax.swing.JLabel jLabelDominio;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBarBarraPrincipal;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuConsClientes;
    private javax.swing.JMenuItem jMenuConsVeiculos;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuDeslogar;
    private javax.swing.JMenuItem jMenuFatLoc;
    private javax.swing.JMenuItem jMenuItemCadasCliente;
    private javax.swing.JMenuItem jMenuItemCadasVeiculo;
    private javax.swing.JMenuItem jMenuItemDevolver;
    private javax.swing.JMenuItem jMenuItemLocar;
    private javax.swing.JMenu jMenuLocacao;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
