/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pbj.loccar.view;

import com.pbj.loccar.control.LocacaoControl;
import com.pbj.loccar.exceptions.DataInvalidaException;
import com.pbj.loccar.util.DataHora;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Akr-Taku
 */
public final class JFrameDevolucao extends javax.swing.JFrame {

    /**
     * Creates new form JFrameDevolucao
     *
     * @param id
     */
    private int id;

    public JFrameDevolucao(int id) {

        initComponents();

        try {
            populaCampos(LocacaoControl.pegaLocacao(id));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Acessar Banco de dados: " + ex, "", JOptionPane.ERROR_MESSAGE);
        }
        txtGetDataHoj.setText(DataHora.getData());
        setaSub();

    }

    public JFrameDevolucao() {
        initComponents();
    }

    private void populaCampos(String[] loc) {
        id = Integer.parseInt(loc[0]);
        txtId.setText(loc[0]);
        txtDescricao.setText(loc[1]);
        txtGetCliente.setText(loc[2]);
        txtGetCPF.setText(loc[3]);
        txtGetVeiculo.setText(loc[4]);
        txtGetPlaca.setText(loc[5]);
        txtGetCateg.setText(loc[6]);
        txtGetDiaria.setText(loc[7]);
        txtGetKmU.setText(loc[8]);
        txtGetDataLoc.setText(DataHora.convertData2(loc[9]));
        txtGetDias.setText(loc[10]);
        txtGetDataEsp.setText(DataHora.convertData2(loc[11]));
        txtGetDesc.setText(loc[12]);
        txtSubTotal.setText(loc[13]);

    }

    private void setaSub() {
        long dias = 0;
        try {
            dias = DataHora.subDias(txtGetDataEsp.getText(), txtGetDataHoj.getText());
            if (dias < 0) {
                dias = 0;
            }
        } catch (DataInvalidaException ex) {

        }

        txtDiasExc.setText(Long.toString(dias));
        try {
            double sub = Double.parseDouble(txtSubTotal.getText());
            double days = Double.parseDouble(txtDiasExc.getText());
            double valorE = Double.parseDouble(txtGetKmU.getText());
            double total = sub + (valorE * days);
            txtGetTotal.setText(Double.toString(total));
        } catch (NumberFormatException e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanelLocDev = new javax.swing.JPanel();
        jPanelInfoLoc = new javax.swing.JPanel();
        jLabelClient = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        txtGetCliente = new javax.swing.JTextField();
        txtGetCPF = new javax.swing.JFormattedTextField();
        jLabelVeic = new javax.swing.JLabel();
        txtGetVeiculo = new javax.swing.JTextField();
        jLabelPlaca = new javax.swing.JLabel();
        txtGetPlaca = new javax.swing.JTextField();
        jLabelCateg = new javax.swing.JLabel();
        txtGetCateg = new javax.swing.JTextField();
        jLabelDiaria = new javax.swing.JLabel();
        txtGetDiaria = new javax.swing.JFormattedTextField();
        jLabelKmU = new javax.swing.JLabel();
        txtGetKmU = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGetDataLoc = new javax.swing.JFormattedTextField();
        jLabelQtdDias = new javax.swing.JLabel();
        txtGetDias = new javax.swing.JTextField();
        jLabelDesco = new javax.swing.JLabel();
        txtGetDesc = new javax.swing.JTextField();
        jLabelid = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelDiasExc1 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JFormattedTextField();
        txtGetDataHoj = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelDiasExc = new javax.swing.JLabel();
        txtDiasExc = new javax.swing.JFormattedTextField();
        txtGetTotal = new javax.swing.JFormattedTextField();
        jLabelTotal = new javax.swing.JLabel();
        txtGetDataEsp = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonDevolver = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Devolver Veículo");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelInfoLoc.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações da Locação"));

        jLabelClient.setText("Cliente");

        jLabelCPF.setText("CPF");

        txtGetCliente.setEditable(false);
        txtGetCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtGetCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGetClienteActionPerformed(evt);
            }
        });

        txtGetCPF.setEditable(false);
        txtGetCPF.setBackground(new java.awt.Color(204, 204, 204));
        try {
            txtGetCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelVeic.setText("Veículo");

        txtGetVeiculo.setEditable(false);
        txtGetVeiculo.setBackground(new java.awt.Color(204, 204, 204));

        jLabelPlaca.setText("Placa");

        txtGetPlaca.setEditable(false);
        txtGetPlaca.setBackground(new java.awt.Color(204, 204, 204));

        jLabelCateg.setText("Categoria");

        txtGetCateg.setEditable(false);
        txtGetCateg.setBackground(new java.awt.Color(204, 204, 204));

        jLabelDiaria.setText("Valor da Diária");

        txtGetDiaria.setEditable(false);
        txtGetDiaria.setBackground(new java.awt.Color(204, 204, 204));
        txtGetDiaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtGetDiaria.setFocusable(false);

        jLabelKmU.setText("Valor Dia Excedente");

        txtGetKmU.setEditable(false);
        txtGetKmU.setBackground(new java.awt.Color(204, 204, 204));
        txtGetKmU.setFocusable(false);

        jLabel9.setText("Data da Locação");

        txtGetDataLoc.setEditable(false);
        txtGetDataLoc.setBackground(new java.awt.Color(204, 204, 204));
        txtGetDataLoc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        txtGetDataLoc.setFocusable(false);

        jLabelQtdDias.setText("Dias");

        txtGetDias.setEditable(false);
        txtGetDias.setBackground(new java.awt.Color(204, 204, 204));
        txtGetDias.setFocusable(false);

        jLabelDesco.setText("Desconto");

        txtGetDesc.setEditable(false);
        txtGetDesc.setBackground(new java.awt.Color(204, 204, 204));
        txtGetDesc.setFocusable(false);

        jLabelid.setText("ID Locação");

        txtDescricao.setEditable(false);
        txtDescricao.setBackground(new java.awt.Color(204, 204, 204));

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(204, 204, 204));

        jLabelDescricao.setText("Descrição da Locação");

        jLabelDiasExc1.setText("SubTotal");

        txtSubTotal.setEditable(false);
        txtSubTotal.setBackground(new java.awt.Color(204, 204, 204));
        txtSubTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtSubTotal.setFocusable(false);

        txtGetDataHoj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        txtGetDataHoj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGetDataHojFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGetDataHojFocusLost(evt);
            }
        });
        txtGetDataHoj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGetDataHojMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtGetDataHojMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtGetDataHojMouseExited(evt);
            }
        });
        txtGetDataHoj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGetDataHojKeyPressed(evt);
            }
        });

        jLabel1.setText("Data de Hoje");

        jLabelDiasExc.setText("Dias Excedentes");

        txtDiasExc.setEditable(false);
        txtDiasExc.setBackground(new java.awt.Color(204, 204, 204));
        txtDiasExc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtDiasExc.setFocusable(false);

        txtGetTotal.setEditable(false);
        txtGetTotal.setBackground(new java.awt.Color(204, 204, 204));
        txtGetTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        txtGetTotal.setFocusable(false);
        txtGetTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGetTotalActionPerformed(evt);
            }
        });

        jLabelTotal.setText("Total");

        txtGetDataEsp.setEditable(false);
        txtGetDataEsp.setBackground(new java.awt.Color(204, 204, 204));
        txtGetDataEsp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        txtGetDataEsp.setFocusable(false);

        jLabel10.setText("Data Esperada");

        javax.swing.GroupLayout jPanelInfoLocLayout = new javax.swing.GroupLayout(jPanelInfoLoc);
        jPanelInfoLoc.setLayout(jPanelInfoLocLayout);
        jPanelInfoLocLayout.setHorizontalGroup(
            jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLocLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoLocLayout.createSequentialGroup()
                            .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelDiasExc1)
                                .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(txtGetDataHoj, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelDiasExc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDiasExc))
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtGetTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelTotal))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelInfoLocLayout.createSequentialGroup()
                            .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelInfoLocLayout.createSequentialGroup()
                                    .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelid)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(48, 48, 48)
                                    .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelDescricao)
                                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanelInfoLocLayout.createSequentialGroup()
                                    .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(txtGetDataLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtGetDias, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelQtdDias))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtGetDataEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelDesco)
                                        .addComponent(txtGetDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInfoLocLayout.createSequentialGroup()
                                        .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCateg)
                                            .addComponent(txtGetCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGetDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelDiaria))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelKmU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtGetKmU)))
                                    .addGroup(jPanelInfoLocLayout.createSequentialGroup()
                                        .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGetVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelVeic))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelPlaca)
                                            .addComponent(txtGetPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelInfoLocLayout.createSequentialGroup()
                        .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelClient)
                            .addComponent(txtGetCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCPF)
                            .addGroup(jPanelInfoLocLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtGetCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(63, Short.MAX_VALUE))))
        );
        jPanelInfoLocLayout.setVerticalGroup(
            jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoLocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelid)
                    .addComponent(jLabelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClient)
                    .addComponent(jLabelCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGetCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGetCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVeic)
                    .addComponent(jLabelPlaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGetVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGetPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCateg)
                    .addComponent(jLabelDiaria)
                    .addComponent(jLabelKmU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGetCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGetDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGetKmU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelQtdDias)
                    .addComponent(jLabelDesco)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGetDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGetDataLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGetDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGetDataEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiasExc1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelDiasExc, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGetDataHoj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiasExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGetTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jButtonDevolver.setText("Devolver");
        jButtonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolverActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLocDevLayout = new javax.swing.GroupLayout(jPanelLocDev);
        jPanelLocDev.setLayout(jPanelLocDevLayout);
        jPanelLocDevLayout.setHorizontalGroup(
            jPanelLocDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocDevLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButtonCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDevolver)
                .addGap(75, 75, 75))
            .addGroup(jPanelLocDevLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInfoLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLocDevLayout.setVerticalGroup(
            jPanelLocDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocDevLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInfoLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanelLocDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDevolver)
                    .addComponent(jButtonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelLocDev, new java.awt.GridBagConstraints());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtGetClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGetClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGetClienteActionPerformed

    private void txtGetTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGetTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGetTotalActionPerformed

    private void jButtonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolverActionPerformed
        // TODO add your handling code here:

        if ("".equals(txtGetDataHoj.getText()) || "".equals(txtDiasExc.getText())) {
            JOptionPane.showMessageDialog(null, "Não é Possivel Salvar Campos Vazios", "", JOptionPane.ERROR_MESSAGE);
        } else {

            int dias = Integer.parseInt(txtDiasExc.getText());
            try {
                LocacaoControl.encerraLocacao(id, dias);

                JOptionPane.showMessageDialog(null, "Devolução Concluída");
                this.dispose();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao Finalizar Locação Acesso ao Banco de dados: " + ex, "", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_jButtonDevolverActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void txtGetDataHojFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGetDataHojFocusLost
        // TODO add your handling code here:
        setaSub();
    }//GEN-LAST:event_txtGetDataHojFocusLost

    private void txtGetDataHojMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGetDataHojMouseExited
        // TODO add your handling code here:
        setaSub();
    }//GEN-LAST:event_txtGetDataHojMouseExited

    private void txtGetDataHojMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGetDataHojMouseEntered
        // TODO add your handling code here:
        setaSub();
    }//GEN-LAST:event_txtGetDataHojMouseEntered

    private void txtGetDataHojFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGetDataHojFocusGained
        // TODO add your handling code here:
        setaSub();
    }//GEN-LAST:event_txtGetDataHojFocusGained

    private void txtGetDataHojMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGetDataHojMouseClicked
        // TODO add your handling code here:
        setaSub();
    }//GEN-LAST:event_txtGetDataHojMouseClicked

    private void txtGetDataHojKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGetDataHojKeyPressed
        // TODO add your handling code here:
        setaSub();
    }//GEN-LAST:event_txtGetDataHojKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameDevolucao().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDevolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCateg;
    private javax.swing.JLabel jLabelClient;
    private javax.swing.JLabel jLabelDesco;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelDiaria;
    private javax.swing.JLabel jLabelDiasExc;
    private javax.swing.JLabel jLabelDiasExc1;
    private javax.swing.JLabel jLabelKmU;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelQtdDias;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelVeic;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JPanel jPanelInfoLoc;
    private javax.swing.JPanel jPanelLocDev;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JFormattedTextField txtDiasExc;
    private javax.swing.JFormattedTextField txtGetCPF;
    private javax.swing.JTextField txtGetCateg;
    private javax.swing.JTextField txtGetCliente;
    private javax.swing.JFormattedTextField txtGetDataEsp;
    private javax.swing.JFormattedTextField txtGetDataHoj;
    private javax.swing.JFormattedTextField txtGetDataLoc;
    private javax.swing.JTextField txtGetDesc;
    private javax.swing.JFormattedTextField txtGetDiaria;
    private javax.swing.JTextField txtGetDias;
    private javax.swing.JTextField txtGetKmU;
    private javax.swing.JTextField txtGetPlaca;
    private javax.swing.JFormattedTextField txtGetTotal;
    private javax.swing.JTextField txtGetVeiculo;
    private javax.swing.JTextField txtId;
    private javax.swing.JFormattedTextField txtSubTotal;
    // End of variables declaration//GEN-END:variables

}
